[package]
name = "solana-rpc"
version = "1.8.2"
description = "Solana RPC"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-rpc"
edition = "2018"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.1"
bs58 = "0.3.1"
crossbeam-channel = "0.4"
dashmap = "4.0.2"
itertools = "0.9.0"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
jsonrpc-ws-server = "18.0.0"
libc = "0.2.81"
log = "0.4.11"
regex = "1.3.9"
serde = "1.0.122"
serde_derive = "1.0.103"
serde_json = "1.0.56"
soketto = "0.6"
solana-account-decoder = { path = "../account-decoder", version = "=1.8.2" }
solana-client = { path = "../client", version = "=1.8.2" }
solana-faucet = { path = "../faucet", version = "=1.8.2" }
solana-gossip = { path = "../gossip", version = "=1.8.2" }
solana-ledger = { path = "../ledger", version = "=1.8.2" }
solana-measure = { path = "../measure", version = "=1.8.2" }
solana-metrics = { path = "../metrics", version = "=1.8.2" }
solana-perf = { path = "../perf", version = "=1.8.2" }
solana-poh = { path = "../poh", version = "=1.8.2" }
solana-runtime = { path = "../runtime", version = "=1.8.2" }
solana-sdk = { path = "../sdk", version = "=1.8.2" }
solana-streamer = { path = "../streamer", version = "=1.8.2" }
solana-storage-bigtable = { path = "../storage-bigtable", version = "=1.8.2" }
solana-transaction-status = { path = "../transaction-status", version = "=1.8.2" }
solana-version = { path = "../version", version = "=1.8.2" }
solana-vote-program = { path = "../programs/vote", version = "=1.8.2" }
spl-token-v2-0 = { package = "spl-token", version = "=3.2.0", features = ["no-entrypoint"] }
stream-cancel = "0.8.1"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec", "compat"] }
zstd = "0.5.1"

[dev-dependencies]
serial_test = "0.4.0"
solana-logger = { path = "../logger", version = "=1.8.2" }
solana-net-utils = { path = "../net-utils", version = "=1.8.2" }
solana-stake-program = { path = "../programs/stake", version = "=1.8.2" }
symlink = "0.1.0"

[lib]
crate-type = ["lib"]
name = "solana_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
